### ISSUE TITLE
Create a "contributing" section in the readme

### ISSUE THREAD

**Issue by roll** [okgreece/tableschema-r#2]
# Overview

It will be great to have a `contributing` section in the readme containing a list of commands required to get started to work on the project. E.g. in Python it contains commands needed to setup virtual environments, install dependencies and run tests.

**Comment by kleanthisk10** [comment]
likewise is in R. I added this section. is it ok so far? of course more details will be added soon.
https://github.com/okgreece/tableschema-r#contributing

**Comment by roll** [comment]
@kleanthisk10 
Thanks. Also it will be super helpful if it includes some hints how to get up and running from scratch. E.g. if someone has never worked with Node.js it will something like this:
```bash
$ git clone https://github.com/frictionlessdata/tableschema-js
$ cd tableschema-js
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash # install NVM
$ nvm install 8 # install Node.js 8
$ nvm use 8
$ npm install
$ npm test
# ALL TESTS PASSED
```

**Comment by kleanthisk10** [comment]
@roll ok! I will add info about how to install R and R studio, the installation of tableschema-r is already included!

**Comment by roll** [comment]
@kleanthisk10 
Thank you!

**Comment by kleanthisk10** [comment]
@roll i've added details about installation of R and RStudio and how to create and run tests! Thank you!

**Comment by roll** [comment]
@kleanthisk10 
Thanks!
