### ISSUE TITLE
Support for type "any"?

### ISSUE THREAD

**Issue by roll** [okgreece/tableschema-r#3]
Hi. Does the lib support type "any" - http://specs.frictionlessdata.io/table-schema/#any?

**Comment by kleanthisk10** [comment]
It is not really possible for an object to be of “Any” type, but it is nevertheless a valid type value. It gets used in certain (rather rare) circumstances, e.g. as.vector(x, "any"), indicating that type coercion should not be done.
https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Any_002dtype

**Comment by roll** [comment]
I mean will be to have a schema descriptor like this?

```json
"fields": [
  {"name": "name", "type": "any"},
]
```

Internally it could handled as string for example. But we just need to do not fail on it.

**Comment by kleanthisk10** [comment]
Yes of course!
